FROM jboss/keycloak:6.0.1
COPY --chown=jboss:root keycloak-eid/truststore.jks /opt/jboss/keycloak/standalone/configuration/
COPY --chown=jboss:root keycloak-eid/keystore.jks /opt/jboss/keycloak/standalone/configuration/
COPY --chown=jboss:root keycloak-eid/standalone-ha.xml /opt/jboss/keycloak/standalone/configuration/
