FROM jboss/keycloak:6.0.1
COPY --chown=jboss:root keycloak/truststore.jks /opt/jboss/keycloak/standalone/configuration/
COPY --chown=jboss:root keycloak/keystore.jks /opt/jboss/keycloak/standalone/configuration/
